version: 2.1

# orbs:
#   docker: circleci/docker@1.5.0

# executors:
#   docker-publisher: 
#     environment:
#       IMAGE_NAME_FE: celnet1/salesapp-frontend
#       IMAGE_NAME_BE: celnet1/salesapp-backend
#     docker: # Each job requires specifying an executor
#     # (either docker, macos, or machine), see
#       - image: circleci/node:latest
#         auth:
#             username: $DOCKERHUB_USERNAME
#             password: $DOCKERHUB_PASSWORD

# jobs:
#     #PulishFE to DockerHub
#     publishLatestFE: 
#       executor: docker-publisher
 
#       steps: 
#         - checkout
#         - setup_remote_docker
#         - run: 
#             name: Publish Frontend Docker Image to Docker Hub
#             command: |
#               echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#               docker build -t $IMAGE_NAME_FE ./frontend
#               docker push $IMAGE_NAME_FE:latest


#     #PublishBE to Dockerhub          
#     publishLatestBE: 
#       executor: docker-publisher
 
#       steps: 
#         - checkout
#         - setup_remote_docker
#         - run: 
#             name: Publish Backend Docker Image to Docker Hub
#             command: |
#               echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#               docker build -t $IMAGE_NAME_BE ./Backend
#               docker push $IMAGE_NAME_BE:latest

#     docker-compose-build:

    
# workflows:
#   version: 2
#   build:
#     jobs:
#        - publishLatestFE
#        - publishLatestBE


